import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import {GeistMono} from "geist/font/mono"
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "git-christmas",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <body
        className={cn(
          "bg-background font-sans antialiased",
          GeistMono.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
