import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { Geist_Mono } from "next/font/google";
import { type Metadata } from "next";

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--geist-mono",
});

export const metadata: Metadata = {
  title: "git-christmas",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body
        className={cn(
          "bg-background font-sans antialiased",
          geistMono.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
